### ISSUE TITLE
Integrate eslint and prettier for better code quality

### ISSUE THREAD

**Issue by m3hari** [m3hari/zemen#2]
Integrate eslint for better code quality

**Comment by m3hari** [comment]
Use Airbnb's eslint config
https://www.npmjs.com/package/eslint-config-airbnb-base

**Comment by m3hari** [comment]
https://github.com/prettier/eslint-config-prettier

**Comment by triartleet** [comment]
Hello, can I have this?

**Comment by m3hari** [comment]
@fllprbt you are very welcome.

**Comment by m3hari** [comment]
Let me know if you need any help

**Comment by linosorice** [comment]
#5 this pull request should fix this

**Comment by triartleet** [comment]
@linosorice due to the Hacktoberfest event could you ask before submitting the PR? I was already on it...

**Comment by m3hari** [comment]
fixed by #5
